DROP DATABASE IF EXISTS employees;
DROP DATABASE IF EXISTS roles;
DROP DATABASE IF EXISTS departments;


CREATE TABLE department(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  department_name VARCHAR(30) NOT NULL
);